version: '3.8'

services:
  infra:
    image: sparrow_cam_infra
    container_name: sparrow_cam_infra
    volumes:
      - ./ansible:/ansible
      - ../app:/app
    working_dir: /ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
